# Generated by Django 4.0.3 on 2023-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=500)),
                ('std_name', models.CharField(blank=True, max_length=900)),
                ('bill_no', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Studentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=500)),
                ('lastname', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=500)),
                ('father_occupation', models.CharField(blank=True, max_length=500)),
                ('mother_name', models.CharField(blank=True, max_length=500)),
                ('mother_occupation', models.CharField(blank=True, max_length=500)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('pincode', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('board', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('mark_10', models.CharField(blank=True, max_length=100)),
                ('mark_11', models.CharField(blank=True, max_length=100)),
                ('mark_12', models.CharField(blank=True, max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('join_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('scholorship', models.CharField(blank=True, max_length=100)),
                ('scholorship_percentage', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('about_studibreeze', models.CharField(blank=True, max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=500, unique=True)),
                ('school_state', models.CharField(blank=True, max_length=200)),
                ('school_district', models.CharField(blank=True, max_length=200)),
                ('studend_image', models.ImageField(blank=True, upload_to='')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=300)),
                ('after_scholorship', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('scholorship_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('remainig_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('std_name', models.CharField(blank=True, max_length=900)),
            ],
        ),
    ]
